<?php echo $this->headTitle() ?>
<?php echo $this->headLink(); ?>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<?=$this->baseUrl()?>">Breaking News Site</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<?=$this->baseUrl()?>">Home</a></li>
      <li><a href="<?=$this->baseUrl()?>/Rss/">Add new RSS</a></li>
    </ul>
  </div>
</nav>
<?php echo $this->layout()->content; ?>